- name: Deploy the Celery worker startup Script
  become: yes
  template: src=celery.j2
        dest=/etc/supervisor/conf.d/celery.conf
            backup=yes
  tags:
     - celery

- name: Re-read the Supervisor config files
  become: yes
  command: supervisorctl reread
  tags:
     - celery

- name: Update Supervisor to add the app in the process group
  become: yes
  command: supervisorctl update
  tags:
     - celery 

